version: "3.8"
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "Welcome123!"
      POSTGRES_DB: "phpappdb"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data: